// Generated by ts-to-zod
import { z } from 'zod';
import { ItemState } from './infrastructure/repositories/items/items-types';

export const itemStateSchema = z.nativeEnum(ItemState);

export const itemSchema = z.object({
  id: z.string(),
  name: z.string().max(30, 'Name cannot be exceed 30 characters long'),
  description: z
    .string()
    .max(50, 'Description cannot be exceed 50 characters')
    .optional(),
  location: z
    .string()
    .max(30, 'Location cannot be exceed 30 characters long')
    .optional(),
  locationLink: z
    .string()
    .url('Location link must be a valid URL including http or https')
    .optional(),
  state: itemStateSchema,
  plannedDate: z.date().optional(),
  creationDate: z.date(),
  completionDate: z.date().optional(),
  referUserId: z.string().optional(),
  votes: z.number().default(0)
});
