import React from 'react';
import { Inter, Lexend } from 'next/font/google';
import './globals.css';
import { NavBar } from '../components/nav-bar/nav-bar';
import clsx from 'clsx';

const inter = Inter({ subsets: ['latin'] });
const lexend = Lexend({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: React.PropsWithChildren) {
  return (
    <html lang="en" data-theme="dark" className="dark">
      <body className={clsx(lexend.className, 'max-w-screen-xl', 'mx-auto')}>
        <NavBar>{children}</NavBar>
      </body>
    </html>
  );
}
